-- =======================================================
-- DO NOT CHANGE THIS FILE !!!
-- IF YOU WANT SOME CHANGES IN THE INITIAL SCHEMA
-- CREATE NEW FILE WITH SUBSEQUENT DATABASE VERSION
-- =======================================================

-- MySQL Script generated by MySQL Workbench
-- Wed 02 Sep 2020 02:34:38 PM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';;
SET GLOBAL log_bin_trust_function_creators = 1;

-- -----------------------------------------------------
-- Schema gamifier
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `avatars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avatars`;;

CREATE TABLE IF NOT EXISTS `avatars`
(
  `id`         INT         NOT NULL AUTO_INCREMENT,
  `img`        VARCHAR(64) NOT NULL,
  `is_generic` TINYINT(1)  NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `img_UNIQUE` ON `avatars` (`img` ASC);;


-- -----------------------------------------------------
-- Table `global_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `global_settings`;;

CREATE TABLE IF NOT EXISTS `global_settings`
(
  `id`              INT         NOT NULL AUTO_INCREMENT,
  `key`             VARCHAR(64) NOT NULL,
  `value`           TEXT        NULL,
  `created_at`      DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `synchronized_at` DATETIME    NULL     DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `key_UNIQUE` ON `global_settings` (`key` ASC);;


-- -----------------------------------------------------
-- Table `languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `languages`;;

CREATE TABLE IF NOT EXISTS `languages`
(
  `id`              INT         NOT NULL AUTO_INCREMENT,
  `language`        VARCHAR(45) NOT NULL,
  `keyboard_layout` VARCHAR(45) NOT NULL,
  `selected`        TINYINT(1)  NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `language_UNIQUE` ON `languages` (`language` ASC);;


-- -----------------------------------------------------
-- Table `phrases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `phrases`;;

CREATE TABLE IF NOT EXISTS `phrases`
(
  `id`     INT          NOT NULL AUTO_INCREMENT,
  `phrase` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `phrase_UNIQUE` ON `phrases` (`phrase` ASC);;


-- -----------------------------------------------------
-- Table `play_sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `play_sessions`;;

CREATE TABLE IF NOT EXISTS `play_sessions`
(
  `id`                   INT          NOT NULL AUTO_INCREMENT,
  `name`                 VARCHAR(255) NOT NULL,
  `is_passed`            TINYINT(1)   NOT NULL DEFAULT 0,
  `is_active`            TINYINT(1)   NOT NULL DEFAULT 0,
  `is_scheduled`         TINYINT(1)   NOT NULL DEFAULT 0,
  `is_autostart_enabled` TINYINT(1)   NOT NULL DEFAULT 0,
  `planned_for`          DATETIME     NULL     DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;


-- -----------------------------------------------------
-- Table `device_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `device_types`;;

CREATE TABLE IF NOT EXISTS `device_types`
(
  `id`   INT         NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `device_typescol_UNIQUE` ON `device_types` (`name` ASC);;


-- -----------------------------------------------------
-- Table `device_type_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `device_type_events`;;

CREATE TABLE IF NOT EXISTS `device_type_events`
(
  `id`             INT          NOT NULL AUTO_INCREMENT,
  `device_type_id` INT          NOT NULL,
  `event_name`     VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_device_events_device_types1`
    FOREIGN KEY (`device_type_id`)
      REFERENCES `device_types` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_device_events_device_types1_idx` ON `device_type_events` (`device_type_id` ASC);;


-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles`;;

CREATE TABLE IF NOT EXISTS `roles`
(
  `id`   INT         NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `role_UNIQUE` ON `roles` (`name` ASC);;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users`;;

CREATE TABLE IF NOT EXISTS `users`
(
  `id`              INT          NOT NULL AUTO_INCREMENT,
  `role_id`         INT          NOT NULL,
  `username`        VARCHAR(255) NOT NULL,
  `name`            VARCHAR(255) NULL DEFAULT NULL,
  `created_at`      DATETIME(6)  NOT NULL,
  `updated_at`      DATETIME(6)  NOT NULL,
  `synchronized_at` DATETIME(6)  NULL DEFAULT NULL,
  `confirmed_at`    DATETIME(6)  NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_table11`
    FOREIGN KEY (`role_id`)
      REFERENCES `roles` (`id`)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `username_UNIQUE` ON `users` (`username` ASC);;

CREATE INDEX `fk_users_table11_idx` ON `users` (`role_id` ASC);;


-- -----------------------------------------------------
-- Table `rfids`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rfids`;;

CREATE TABLE IF NOT EXISTS `rfids`
(
  `id`       INT        NOT NULL AUTO_INCREMENT,
  `value`    BIGINT     NOT NULL,
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `value_UNIQUE` ON `rfids` (`value` ASC);;


-- -----------------------------------------------------
-- Table `players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `players`;;

CREATE TABLE IF NOT EXISTS `players`
(
  `id`              BIGINT       NOT NULL AUTO_INCREMENT,
  `user_id`         INT          NOT NULL,
  `rfid_id`         INT          NULL     DEFAULT NULL,
  `avatar_id`       INT          NULL     DEFAULT NULL,
  `sync_id`         VARCHAR(254) NULL     DEFAULT NULL,
  `session_id`      INT          NULL,
  `full_name`       VARCHAR(255) NULL     DEFAULT NULL,
  `name`            VARCHAR(255) NOT NULL,
  `is_default`      TINYINT(1)   NOT NULL DEFAULT 0,
  `created_at`      DATETIME(6)  NOT NULL,
  `updated_at`      DATETIME(6)  NOT NULL,
  `synchronized_at` DATETIME(6)  NULL     DEFAULT NULL,
  `confirmed_at`    DATETIME(6)  NULL     DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_players_avatars1`
    FOREIGN KEY (`avatar_id`)
      REFERENCES `avatars` (`id`)
      ON DELETE SET NULL
      ON UPDATE CASCADE,
  CONSTRAINT `fk_players_users1`
    FOREIGN KEY (`user_id`)
      REFERENCES `users` (`id`)
          ON DELETE CASCADE
          ON UPDATE CASCADE,
  CONSTRAINT `fk_players_rfids1`
    FOREIGN KEY (`rfid_id`)
      REFERENCES `rfids` (`id`)
      ON DELETE SET NULL
      ON UPDATE CASCADE,
  CONSTRAINT `fk_players_session_id`
    FOREIGN KEY (`session_id`)
      REFERENCES `play_sessions` (`id`)
      ON DELETE RESTRICT
      ON UPDATE RESTRICT
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_players_users1_idx` ON `players` (`user_id` ASC);;

CREATE INDEX `fk_players_avatars1_idx` ON `players` (`avatar_id` ASC);;

CREATE INDEX `fk_players_rfids1_idx` ON `players` (`rfid_id` ASC);;

CREATE UNIQUE INDEX `rfid_id_UNIQUE` ON `players` (`rfid_id` ASC);;

CREATE UNIQUE INDEX `userId_playerName_pair_UNIQUE` ON `players` (`user_id` ASC, `name` ASC);;

CREATE UNIQUE INDEX `sync_id_UNIQUE` ON `players` (`sync_id` ASC);;

CREATE INDEX `fk_players_session_id_idx` ON `players` (`session_id` ASC);;


-- -----------------------------------------------------
-- Table `teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teams`;;

CREATE TABLE IF NOT EXISTS `teams`
(
  `id`              INT          NOT NULL AUTO_INCREMENT,
  `play_session_id` INT          NOT NULL,
  `name`            VARCHAR(128) NOT NULL,
  `color`           VARCHAR(32)  NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_teams_events1`
    FOREIGN KEY (`play_session_id`)
      REFERENCES `play_sessions` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_teams_events1_idx` ON `teams` (`play_session_id` ASC);;


-- -----------------------------------------------------
-- Table `players_teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `players_teams`;;

CREATE TABLE IF NOT EXISTS `players_teams`
(
  `id`        INT    NOT NULL AUTO_INCREMENT,
  `team_id`   INT    NOT NULL,
  `player_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `team_id`, `player_id`),
  CONSTRAINT `fk_players_teams_players1`
    FOREIGN KEY (`player_id`)
      REFERENCES `players` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  CONSTRAINT `fk_players_teams_teams1`
    FOREIGN KEY (`team_id`)
      REFERENCES `teams` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_players_teams_teams1_idx` ON `players_teams` (`team_id` ASC);;

CREATE INDEX `fk_players_teams_players1_idx` ON `players_teams` (`player_id` ASC);;


-- -----------------------------------------------------
-- Table `videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videos`;;

CREATE TABLE IF NOT EXISTS `videos`
(
  `id`              INT          NOT NULL AUTO_INCREMENT,
  `filename`        VARCHAR(128) NOT NULL,
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `synchronized_at` DATETIME     NULL     DEFAULT NULL,
  `sync_id`         BINARY(16)   NULL     DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `filename_UNIQUE` ON `videos` (`filename` ASC);;


-- -----------------------------------------------------
-- Table `games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `games`;;

CREATE TABLE IF NOT EXISTS `games`
(
  `id`              INT          NOT NULL AUTO_INCREMENT,
  `video_id`        INT          NULL,
  `name`            VARCHAR(128) NOT NULL,
  `position`        INT          NOT NULL,
  `background`      VARCHAR(255) NULL,
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `synchronized_at` DATETIME     NULL     DEFAULT NULL,
  `sync_id`         BINARY(16)   NULL     DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_games_videos1`
    FOREIGN KEY (`video_id`)
      REFERENCES `videos` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `name_UNIQUE` ON `games` (`name` ASC);;

CREATE INDEX `fk_games_videos1_idx` ON `games` (`video_id` ASC);;


-- -----------------------------------------------------
-- Table `games_logic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `games_logic`;;

CREATE TABLE IF NOT EXISTS `games_logic`
(
  `id`    INT          NOT NULL AUTO_INCREMENT,
  `class` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `class_UNIQUE` ON `games_logic` (`class` ASC);;


-- -----------------------------------------------------
-- Table `sub_games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sub_games`;;

CREATE TABLE IF NOT EXISTS `sub_games`
(
  `id`               INT          NOT NULL AUTO_INCREMENT,
  `game_id`          INT          NOT NULL,
  `game_logic_id`    INT          NULL,
  `name`             VARCHAR(255) NOT NULL,
  `coefficient`      FLOAT        NULL     DEFAULT NULL,
  `is_active`        TINYINT(1)   NOT NULL DEFAULT 0,
  `raw_scores`       VARCHAR(255) NULL,
  `description`      TEXT         NULL,
  `is_time_excluded` TINYINT(1)   NOT NULL DEFAULT 0,
  `created_at`       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `synchronized_at`  DATETIME     NULL     DEFAULT NULL,
  `sync_id`          BINARY(16)   NULL     DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_games_game_logic1`
    FOREIGN KEY (`game_logic_id`)
      REFERENCES `games_logic` (`id`)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  CONSTRAINT `fk_sub_games_games1`
    FOREIGN KEY (`game_id`)
      REFERENCES `games` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `name_UNIQUE` ON `sub_games` (`name` ASC);;

CREATE INDEX `fk_games_game_logic1_idx` ON `sub_games` (`game_logic_id` ASC);;

CREATE INDEX `fk_sub_games_games1_idx` ON `sub_games` (`game_id` ASC);;


-- -----------------------------------------------------
-- Table `devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devices`;;

CREATE TABLE IF NOT EXISTS `devices`
(
  `id`                  BIGINT                                 NOT NULL AUTO_INCREMENT,
  `uid`                 VARCHAR(128)                           NOT NULL,
  `type_id`             INT                                    NOT NULL,
  `virtual_to`          BIGINT(20)                             NULL     DEFAULT NULL,
  `anydesk_id`          INT                                    NULL     DEFAULT NULL,
  `ip`                  VARCHAR(64)                            NOT NULL,
  `status`              ENUM ('ONLINE', 'OFFLINE', 'UPDATING') NOT NULL DEFAULT 'OFFLINE',
  `hw_version`          VARCHAR(32)                            NULL,
  `fw_version`          VARCHAR(32)                            NULL,
  `fw_date`             DATETIME                               NULL,
  `comment`             VARCHAR(255)                           NULL     DEFAULT NULL,
  `is_ok_health_status` TINYINT(1)                             NOT NULL DEFAULT 1,
  `is_need_update`      TINYINT(1)                             NOT NULL DEFAULT 0,
  `synced`              TINYINT(1)                             NOT NULL DEFAULT 0,
  `ssh_username`        VARCHAR(255)                           NULL     DEFAULT NULL,
  `ssh_password`        VARCHAR(255)                           NULL     DEFAULT NULL,
  `alias`               VARCHAR(255)                           NULL     DEFAULT NULL,
  `created_at`          DATETIME                               NOT NULL DEFAULT current_timestamp,
  `deleted_at`          DATETIME                               NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_devices_device_types1`
    FOREIGN KEY (`type_id`)
      REFERENCES `device_types` (`id`)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  CONSTRAINT `fk_devices_1`
    FOREIGN KEY (`virtual_to`)
      REFERENCES `devices` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `uid_UNIQUE` ON `devices` (`uid` ASC);;

CREATE INDEX `fk_devices_device_types1_idx` ON `devices` (`type_id` ASC);;

CREATE INDEX `fk_devices_1_idx` ON `devices` (`virtual_to` ASC);;


-- -----------------------------------------------------
-- Table `games_devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `games_devices`;;

CREATE TABLE IF NOT EXISTS `games_devices`
(
  `id`          BIGINT       NOT NULL AUTO_INCREMENT,
  `sub_game_id` INT          NOT NULL,
  `device_id`   BIGINT       NOT NULL,
  `device_name` VARCHAR(128) NOT NULL,
  `enabled`     TINYINT(1)   NOT NULL DEFAULT 1,
  `position`    INT          NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_games_has_devices_devices1`
    FOREIGN KEY (`device_id`)
      REFERENCES `devices` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  CONSTRAINT `fk_games_has_devices_games1`
    FOREIGN KEY (`sub_game_id`)
      REFERENCES `sub_games` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_games_has_devices_devices1_idx` ON `games_devices` (`device_id` ASC);;

CREATE INDEX `fk_games_has_devices_games1_idx` ON `games_devices` (`sub_game_id` ASC);;

CREATE UNIQUE INDEX `games_devices_unique_pair` ON `games_devices` (`sub_game_id` ASC, `device_id` ASC);;


-- -----------------------------------------------------
-- Table `plays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `plays`;;

CREATE TABLE IF NOT EXISTS `plays`
(
  `id`               BIGINT     NOT NULL AUTO_INCREMENT,
  `sub_game_id`      INT        NOT NULL,
  `player_id`        BIGINT     NULL,
  `team_id`          INT        NULL,
  `play_session_id`  INT        NULL,
  `rfid_id`          INT        NULL,
  `score`            BIGINT     NOT NULL,
  `remote_score`     BIGINT     NOT NULL DEFAULT 0,
  `time`             BIGINT     NOT NULL,
  `coefficient`      FLOAT      NOT NULL DEFAULT 1,
  `is_time_excluded` TINYINT(1) NOT NULL DEFAULT 0,
  `is_deleted`       TINYINT(1) NOT NULL DEFAULT 0,
  `is_synced`        TINYINT(1) NOT NULL DEFAULT 0,
  `created_at`       DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_plays_events1`
    FOREIGN KEY (`play_session_id`)
      REFERENCES `play_sessions` (`id`)
      ON DELETE SET NULL
      ON UPDATE CASCADE,
  CONSTRAINT `fk_plays_players1`
    FOREIGN KEY (`player_id`)
      REFERENCES `players` (`id`)
      ON DELETE SET NULL
      ON UPDATE CASCADE,
  CONSTRAINT `fk_plays_rfids1`
    FOREIGN KEY (`rfid_id`)
      REFERENCES `rfids` (`id`)
      ON DELETE SET NULL
      ON UPDATE CASCADE,
  CONSTRAINT `fk_plays_games1`
    FOREIGN KEY (`sub_game_id`)
      REFERENCES `sub_games` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  CONSTRAINT `fk_plays_teams1`
    FOREIGN KEY (`team_id`)
      REFERENCES `teams` (`id`)
      ON DELETE SET NULL
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_plays_rfids1_idx` ON `plays` (`rfid_id` ASC);;

CREATE INDEX `fk_plays_players1_idx` ON `plays` (`player_id` ASC);;

CREATE INDEX `fk_plays_teams1_idx` ON `plays` (`team_id` ASC);;

CREATE INDEX `fk_plays_events1_idx` ON `plays` (`play_session_id` ASC);;

CREATE INDEX `fk_plays_games1_idx` ON `plays` (`sub_game_id` ASC);;


-- -----------------------------------------------------
-- Table `translations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `translations`;;

CREATE TABLE IF NOT EXISTS `translations`
(
  `id`           INT          NOT NULL AUTO_INCREMENT,
  `languages_id` INT          NOT NULL,
  `phrases_id`   INT          NOT NULL,
  `translation`  VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_translations_languages1`
    FOREIGN KEY (`languages_id`)
      REFERENCES `languages` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  CONSTRAINT `fk_translations_phrases1`
    FOREIGN KEY (`phrases_id`)
      REFERENCES `phrases` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_translations_languages1_idx` ON `translations` (`languages_id` ASC);;

CREATE INDEX `fk_translations_phrases1_idx` ON `translations` (`phrases_id` ASC);;

CREATE UNIQUE INDEX `translation_unique_pair` ON `translations` (`languages_id` ASC, `phrases_id` ASC);;


-- -----------------------------------------------------
-- Table `adjectives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adjectives`;;

CREATE TABLE IF NOT EXISTS `adjectives`
(
  `id`    INT          NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `name_UNIQUE` ON `adjectives` (`value` ASC);;


-- -----------------------------------------------------
-- Table `nouns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nouns`;;

CREATE TABLE IF NOT EXISTS `nouns`
(
  `id`    INT          NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `value_UNIQUE` ON `nouns` (`value` ASC);;


-- -----------------------------------------------------
-- Table `device_settings_keys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `device_settings_keys`;;

CREATE TABLE IF NOT EXISTS `device_settings_keys`
(
  `id`  INT         NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `device_key_UNIQUE` ON `device_settings_keys` (`key` ASC);;


-- -----------------------------------------------------
-- Table `device_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `device_settings`;;

CREATE TABLE IF NOT EXISTS `device_settings`
(
  `device_id`       BIGINT       NOT NULL,
  `settings_key_id` INT          NOT NULL,
  `value`           VARCHAR(255) NULL,
  `description`     TEXT         NULL     DEFAULT NULL,
  `data_type`       VARCHAR(45)  NULL     DEFAULT NULL,
  `constraints`     VARCHAR(255) NULL     DEFAULT NULL,
  `hide`            VARCHAR(45)  NOT NULL DEFAULT 0,
  PRIMARY KEY (`device_id`, `settings_key_id`),
  CONSTRAINT `fk_devices_has_device_settings_keys_devices1`
    FOREIGN KEY (`device_id`)
      REFERENCES `devices` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  CONSTRAINT `fk_devices_has_device_settings_keys_device_settings_keys1`
    FOREIGN KEY (`settings_key_id`)
      REFERENCES `device_settings_keys` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_devices_has_device_settings_keys_device_settings_keys1_idx` ON `device_settings` (`settings_key_id` ASC);;

CREATE INDEX `fk_devices_has_device_settings_keys_devices1_idx` ON `device_settings` (`device_id` ASC);;

CREATE UNIQUE INDEX `index4` ON `device_settings` (`device_id` ASC, `settings_key_id` ASC);;


-- -----------------------------------------------------
-- Table `devices_health_status_keys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devices_health_status_keys`;;

CREATE TABLE IF NOT EXISTS `devices_health_status_keys`
(
  `id`                  BIGINT                           NOT NULL AUTO_INCREMENT,
  `device_type_id`      INT                              NOT NULL,
  `name`                VARCHAR(255)                     NOT NULL,
  `min`                 DOUBLE                           NULL,
  `max`                 DOUBLE                           NULL,
  `type`                ENUM ('INT', 'DOUBLE', 'STRING') NOT NULL DEFAULT 'INT',
  `is_aggregated`       TINYINT(1)                       NOT NULL DEFAULT 1,
  `is_show_graphically` TINYINT(1)                       NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_devices_health_status_keys_device_types1`
    FOREIGN KEY (`device_type_id`)
      REFERENCES `device_types` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_devices_health_status_keys_device_types1_idx` ON `devices_health_status_keys` (`device_type_id` ASC);;


-- -----------------------------------------------------
-- Table `devices_health_status_values`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devices_health_status_values`;;

CREATE TABLE IF NOT EXISTS `devices_health_status_values`
(
  `id`               BIGINT       NOT NULL AUTO_INCREMENT,
  `device_id`        BIGINT       NOT NULL,
  `health_status_id` BIGINT       NOT NULL,
  `value`            VARCHAR(255) NOT NULL,
  `created_at`       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_devices_health_values_1`
    FOREIGN KEY (`device_id`)
      REFERENCES `devices` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  CONSTRAINT `fk_devices_health_values_2`
    FOREIGN KEY (`health_status_id`)
      REFERENCES `devices_health_status_keys` (`id`)
      ON DELETE RESTRICT
      ON UPDATE RESTRICT
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `health_status_id_idx` ON `devices_health_status_values` (`health_status_id` ASC);;

CREATE INDEX `device_id_idx` ON `devices_health_status_values` (`device_id` ASC);;


-- -----------------------------------------------------
-- Table `game_logic_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `game_logic_settings`;;

CREATE TABLE IF NOT EXISTS `game_logic_settings`
(
  `id`          INT          NOT NULL AUTO_INCREMENT,
  `logic_id`    INT          NOT NULL,
  `sub_game_id` INT          NULL,
  `setting`     VARCHAR(128) NOT NULL,
  `value`       VARCHAR(255) NULL,
  `description` TEXT         NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_game_logic_settings_games_logic1`
    FOREIGN KEY (`logic_id`)
      REFERENCES `games_logic` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_logic_settings_sub_games1`
    FOREIGN KEY (`sub_game_id`)
      REFERENCES `sub_games` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_game_logic_settings_games_logic1_idx` ON `game_logic_settings` (`logic_id` ASC);;

CREATE INDEX `fk_game_logic_settings_sub_games1_idx` ON `game_logic_settings` (`sub_game_id` ASC);;


-- -----------------------------------------------------
-- Table `device_updates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `device_updates`;;

CREATE TABLE IF NOT EXISTS `device_updates`
(
  `id`                 INT          NOT NULL AUTO_INCREMENT,
  `device_type_id`     INT          NOT NULL,
  `file`               VARCHAR(128) NOT NULL,
  `lowest_hw_version`  VARCHAR(45)  NOT NULL,
  `highest_hw_version` VARCHAR(45)  NOT NULL,
  `fw_version`         VARCHAR(32)  NOT NULL,
  `fw_date`            DATETIME     NULL,
  `active`             TINYINT(1)   NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_device_updates_device_types1`
    FOREIGN KEY (`device_type_id`)
      REFERENCES `device_types` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_device_updates_device_types1_idx` ON `device_updates` (`device_type_id` ASC);;


-- -----------------------------------------------------
-- Table `wavier_parent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wavier_parent`;;

CREATE TABLE IF NOT EXISTS `wavier_parent`
(
  `id`         BIGINT                  NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45)             NOT NULL,
  `last_name`  VARCHAR(45)             NOT NULL,
  `gender`     ENUM ('Male', 'Female') NOT NULL,
  `phone`      VARCHAR(45)             NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;


-- -----------------------------------------------------
-- Table `wavier_child`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wavier_child`;;

CREATE TABLE IF NOT EXISTS `wavier_child`
(
  `id`         BIGINT                  NOT NULL AUTO_INCREMENT,
  `parent_id`  BIGINT                  NOT NULL,
  `first_name` VARCHAR(45)             NOT NULL,
  `gender`     ENUM ('Male', 'Female') NOT NULL,
  `birthday`   DATE                    NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_children_1`
    FOREIGN KEY (`parent_id`)
      REFERENCES `wavier_parent` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `index2` ON `wavier_child` (`parent_id` ASC);;


-- -----------------------------------------------------
-- Table `device_update_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `device_update_history`;;

CREATE TABLE IF NOT EXISTS `device_update_history`
(
  `id`                INT          NOT NULL AUTO_INCREMENT,
  `device_updates_id` INT          NOT NULL,
  `devices_id`        BIGINT       NOT NULL,
  `error_msg`         VARCHAR(255) NULL     DEFAULT NULL,
  `last_hw_version`   VARCHAR(32)  NULL,
  `last_fw_version`   VARCHAR(32)  NULL,
  `last_fw_date`      DATETIME     NULL,
  `created_at`        DATETIME     NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_device_update_history_device_updates1`
    FOREIGN KEY (`device_updates_id`)
      REFERENCES `device_updates` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_device_update_history_devices1`
    FOREIGN KEY (`devices_id`)
      REFERENCES `devices` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_device_update_history_device_updates1_idx` ON `device_update_history` (`device_updates_id` ASC);;

CREATE INDEX `fk_device_update_history_devices1_idx` ON `device_update_history` (`devices_id` ASC);;


-- -----------------------------------------------------
-- Table `device_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `device_logs`;;

CREATE TABLE IF NOT EXISTS `device_logs`
(
  `id`           BIGINT                                                                                          NOT NULL AUTO_INCREMENT,
  `device_id`    BIGINT                                                                                          NOT NULL,
  `level`        ENUM ('SEVERE', 'CRITICAL', 'ERROR', 'WARNING', 'NOTICE', 'INFO', 'STATUS', 'DEBUG', 'UNKNOWN') NOT NULL,
  `message`      VARCHAR(255)                                                                                    NULL,
  `description`  TEXT                                                                                            NULL,
  `file`         VARCHAR(255)                                                                                    NULL,
  `is_dismissed` TINYINT(1)                                                                                      NOT NULL DEFAULT 0,
  `created_at`   DATETIME                                                                                        NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_device_logs_1`
    FOREIGN KEY (`device_id`)
      REFERENCES `devices` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_device_logs_1_idx` ON `device_logs` (`device_id` ASC);;


-- -----------------------------------------------------
-- Table `third_parties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `third_parties`;;

CREATE TABLE IF NOT EXISTS `third_parties`
(
  `id`   INT          NOT NULL AUTO_INCREMENT,
  `uid`  VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;;


-- -----------------------------------------------------
-- Table `admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admins`;;

CREATE TABLE IF NOT EXISTS `admins`
(
  `id`              INT          NOT NULL AUTO_INCREMENT,
  `third_party_id`  INT          NULL,
  `username`        VARCHAR(255) NOT NULL DEFAULT 'admin',
  `password`        VARCHAR(128) NOT NULL,
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `synchronized_at` DATETIME     NULL     DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_admins_1`
    FOREIGN KEY (`third_party_id`)
      REFERENCES `third_parties` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `username_UNIQUE` ON `admins` (`username` ASC);;

CREATE INDEX `fk_admins_1_idx` ON `admins` (`third_party_id` ASC);;


-- -----------------------------------------------------
-- Table `wavier_form_fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wavier_form_fields`;;

CREATE TABLE IF NOT EXISTS `wavier_form_fields`
(
  `id`          INT                                                NOT NULL AUTO_INCREMENT,
  `name`        VARCHAR(255)                                       NOT NULL,
  `field_type`  ENUM ('TEXT', 'NUMBER', 'SELECT', 'RADIO', 'DATE') NOT NULL DEFAULT 'TEXT',
  `person_type` ENUM ('SIGNED', 'DEPENDANT')                       NOT NULL,
  `constraint`  VARCHAR(255)                                       NULL,
  `is_include`  TINYINT(1)                                         NOT NULL DEFAULT 1,
  `is_required` TINYINT(1)                                         NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;;

CREATE UNIQUE INDEX `uq_wavier_form_fields` ON `wavier_form_fields` (`name` ASC, `person_type` ASC);;


-- -----------------------------------------------------
-- Table `wavier_fillings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wavier_fillings`;;

CREATE TABLE IF NOT EXISTS `wavier_fillings`
(
  `id`         BIGINT   NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;;


-- -----------------------------------------------------
-- Table `wavier_values`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wavier_values`;;

CREATE TABLE IF NOT EXISTS `wavier_values`
(
  `id`         BIGINT       NOT NULL AUTO_INCREMENT,
  `field_id`   INT          NOT NULL,
  `filling_id` BIGINT       NOT NULL,
  `uq_id`      VARCHAR(45)  NOT NULL,
  `value`      VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_wavier_field_id`
    FOREIGN KEY (`field_id`)
      REFERENCES `wavier_form_fields` (`id`)
      ON DELETE RESTRICT
      ON UPDATE RESTRICT,
  CONSTRAINT `fk_wavier_values_1`
    FOREIGN KEY (`filling_id`)
      REFERENCES `wavier_fillings` (`id`)
      ON DELETE RESTRICT
      ON UPDATE RESTRICT
)
  ENGINE = InnoDB;;

CREATE INDEX `fk_wavier_field_id_idx` ON `wavier_values` (`field_id` ASC);;

CREATE UNIQUE INDEX `uq_wavier_values` ON `wavier_values` (`uq_id` ASC, `field_id` ASC);;

CREATE INDEX `fk_wavier_values_1_idx` ON `wavier_values` (`filling_id` ASC);;


-- -----------------------------------------------------
-- Table `blacklist_words`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blacklist_words`;;

CREATE TABLE IF NOT EXISTS `blacklist_words`
(
  `id`   INT          NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE UNIQUE INDEX `word_UNIQUE` ON `blacklist_words` (`word` ASC);;


-- -----------------------------------------------------
-- Table `admin_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_settings`;;

CREATE TABLE IF NOT EXISTS `admin_settings`
(
  `id`       INT          NOT NULL AUTO_INCREMENT,
  `admin_id` INT          NOT NULL,
  `key`      VARCHAR(128) NOT NULL,
  `value`    LONGTEXT     NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_admin_id`
    FOREIGN KEY (`admin_id`)
      REFERENCES `admins` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_admin_id_idx` ON `admin_settings` (`admin_id` ASC);;

CREATE UNIQUE INDEX `uq_admin_id_key` ON `admin_settings` (`admin_id` ASC, `key` ASC);;


-- -----------------------------------------------------
-- Table `admin_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_roles`;;

CREATE TABLE IF NOT EXISTS `admin_roles`
(
  `id`       INT                                                                              NOT NULL AUTO_INCREMENT,
  `admin_id` INT                                                                              NOT NULL,
  `role`     ENUM ('ADMIN', 'USER', 'DEVELOPER', 'ADMIN_SIM', 'SUPER_ADMIN', 'ROLE_OPERATOR') NOT NULL DEFAULT 'ADMIN',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Roles_1`
    FOREIGN KEY (`admin_id`)
      REFERENCES `admins` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;;

CREATE INDEX `fk_Roles_1_idx` ON `admin_roles` (`admin_id` ASC);;

CREATE UNIQUE INDEX `admin_id_role_uq` ON `admin_roles` (`admin_id` ASC, `role` ASC);;


-- -----------------------------------------------------
-- Table `game_play_modes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `game_play_modes`;;

CREATE TABLE IF NOT EXISTS `game_play_modes`
(
  `id`                    INT          NOT NULL AUTO_INCREMENT,
  `priority`              INT          NOT NULL,
  `default_play_duration` INT          NOT NULL COMMENT 'the play_time value is in minutes',
  `default_play_count`    INT          NOT NULL,
  `name`                  VARCHAR(200) NOT NULL,
  `unnamed`               TINYINT(1)   NOT NULL,
  `edited_by`             INT          NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_edited_by`
    FOREIGN KEY (`edited_by`)
      REFERENCES `admins` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_edited_by_idx` ON `game_play_modes` (`edited_by` ASC);;


-- -----------------------------------------------------
-- Table `game_mode_params`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `game_mode_params`;;

CREATE TABLE IF NOT EXISTS `game_mode_params`
(
  `id`                INT NOT NULL AUTO_INCREMENT,
  `game_play_mode_id` INT NOT NULL,
  `subgame_id`        INT NOT NULL,
  `play_count`        INT NOT NULL,
  `play_time`         INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_game_play_mode_idx`
    FOREIGN KEY (`game_play_mode_id`)
      REFERENCES `game_play_modes` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  CONSTRAINT `kf_sub_game_id`
    FOREIGN KEY (`subgame_id`)
      REFERENCES `sub_games` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `kf_sub_game_id_idx` ON `game_mode_params` (`subgame_id` ASC);;


-- -----------------------------------------------------
-- Table `game_play_mode_applications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `game_play_mode_applications`;;

CREATE TABLE IF NOT EXISTS `game_play_mode_applications`
(
  `id`                   INT      NOT NULL AUTO_INCREMENT,
  `game_play_mode_id`    INT      NOT NULL,
  `player_id`            BIGINT   NULL,
  `session_id`           INT      NULL,
  `created_at`           DATETIME NULL,
  `starts_at`            DATETIME NULL,
  `expires_at`           DATETIME NULL,
  `max_total_play_count` INT      NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_game_play_mode_id`
    FOREIGN KEY (`game_play_mode_id`)
      REFERENCES `game_play_modes` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  CONSTRAINT `fk_player_id`
    FOREIGN KEY (`player_id`)
      REFERENCES `players` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_session_id`
    FOREIGN KEY (`session_id`)
      REFERENCES `play_sessions` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_player_id_idx` ON `game_play_mode_applications` (`player_id` ASC);;

CREATE INDEX `fk_session_id_idx` ON `game_play_mode_applications` (`session_id` ASC);;


-- -----------------------------------------------------
-- Table `admin_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_permissions`;;

CREATE TABLE IF NOT EXISTS `admin_permissions`
(
  `id`       INT          NOT NULL AUTO_INCREMENT,
  `admin_id` INT          NOT NULL,
  `name`     VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Permissions_1`
    FOREIGN KEY (`admin_id`)
      REFERENCES `admins` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;;

CREATE INDEX `fk_Permissions_1_idx` ON `admin_permissions` (`admin_id` ASC);;

CREATE UNIQUE INDEX `admin_id_permission_uq` ON `admin_permissions` (`admin_id` ASC, `name` ASC);;


-- -----------------------------------------------------
-- Table `activity_log_files_sync`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `activity_log_files_sync`;;

CREATE TABLE IF NOT EXISTS `activity_log_files_sync`
(
  `id`              BIGINT       NOT NULL AUTO_INCREMENT,
  `file_name`       VARCHAR(100) NOT NULL,
  `synchronized_at` DATETIME     NULL     DEFAULT NULL,
  `is_synced`       TINYINT(1)   NOT NULL DEFAULT 0,
  `is_write_ended`  TINYINT(1)   NOT NULL DEFAULT 0,
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;


-- -----------------------------------------------------
-- Table `operator_wristbands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `operator_wristbands`;;

CREATE TABLE IF NOT EXISTS `operator_wristbands`
(
  `id`         INT      NOT NULL AUTO_INCREMENT,
  `admin_id`   INT      NOT NULL,
  `rfid_id`    INT      NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_operator_wristbands_admins`
    FOREIGN KEY (`admin_id`)
      REFERENCES `admins` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  CONSTRAINT `fk_operator_wristbands_rfids`
    FOREIGN KEY (`rfid_id`)
      REFERENCES `rfids` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_operator_wristbands_admins_idx` ON `operator_wristbands` (`admin_id` ASC);;

CREATE INDEX `fk_operator_wristbands_rfids_idx` ON `operator_wristbands` (`rfid_id` ASC);;


-- -----------------------------------------------------
-- Table `sessions_devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sessions_devices`;;

CREATE TABLE IF NOT EXISTS `sessions_devices`
(
  `id`         INT    NOT NULL AUTO_INCREMENT,
  `session_id` INT    NOT NULL,
  `device_id`  BIGINT NOT NULL,
  PRIMARY KEY (`id`, `session_id`, `device_id`),
  CONSTRAINT `fk_sessions`
    FOREIGN KEY (`session_id`)
      REFERENCES `play_sessions` (`id`)
      ON DELETE RESTRICT
      ON UPDATE RESTRICT,
  CONSTRAINT `fk_devices`
    FOREIGN KEY (`device_id`)
      REFERENCES `devices` (`id`)
      ON DELETE RESTRICT
      ON UPDATE RESTRICT
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf16;;

CREATE INDEX `fk_sessions_idx` ON `sessions_devices` (`session_id` ASC);;

CREATE INDEX `fk_devices_idx` ON `sessions_devices` (`device_id` ASC);;


DROP TRIGGER IF EXISTS `users_AFTER_UPDATE`;;
CREATE DEFINER = CURRENT_USER TRIGGER `users_AFTER_UPDATE`
  AFTER UPDATE
  ON `users`
  FOR EACH ROW
BEGIN
  UPDATE `players` SET `updated_at` = CURRENT_TIMESTAMP WHERE `user_id` = NEW.`id`;
END;;

CREATE OR REPLACE FUNCTION ver(version VARCHAR(128)) RETURNS INT
RETURN
  (INET_ATON(
      CONCAT(
          version,
          REPEAT(
              '.0',
              3 - CHAR_LENGTH(version) + CHAR_LENGTH(REPLACE(version, '.', ''))
            )
        )
    ));;


CREATE OR REPLACE VIEW on_belay_devices AS
SELECT d.id,
       d.uid,
       d.status,
       GROUP_CONCAT(CASE WHEN k.name = 'tank_px' THEN v.value END ORDER BY v.created_at DESC LIMIT 1)     AS 'tank_px',
       GROUP_CONCAT(CASE WHEN k.name = 'tank_lvl' THEN v.value END ORDER BY v.created_at DESC LIMIT 1)    AS 'tank_lvl',
       GROUP_CONCAT(CASE WHEN k.name = 'piston_a_px' THEN v.value END ORDER BY v.created_at DESC LIMIT
                    1)                                                                                    AS 'piston_a_px',
       GROUP_CONCAT(CASE WHEN k.name = 'piston_b_px' THEN v.value END ORDER BY v.created_at DESC LIMIT
                    1)                                                                                    AS 'piston_b_px',
       GROUP_CONCAT(CASE WHEN k.name = 'piston_diff' THEN v.value END ORDER BY v.created_at DESC LIMIT
                    1)                                                                                    AS 'piston_diff'
FROM devices_health_status_keys k
       LEFT JOIN devices_health_status_values v on k.id = v.health_status_id
       LEFT JOIN devices d on v.device_id = d.id
WHERE d.type_id = 4
GROUP BY device_id
ORDER BY device_id;;

CREATE OR REPLACE VIEW on_belay_device_logs AS
SELECT d.id,
       v.created_at                                                                                       AS `date`,
       GROUP_CONCAT(CASE WHEN k.name = 'tank_px' THEN v.value END ORDER BY v.created_at DESC LIMIT 1)     AS 'tank_px',
       GROUP_CONCAT(CASE WHEN k.name = 'tank_lvl' THEN v.value END ORDER BY v.created_at DESC LIMIT 1)    AS 'tank_lvl',
       GROUP_CONCAT(CASE WHEN k.name = 'piston_a_px' THEN v.value END ORDER BY v.created_at DESC LIMIT
                    1)                                                                                    AS 'piston_a_px',
       GROUP_CONCAT(CASE WHEN k.name = 'piston_b_px' THEN v.value END ORDER BY v.created_at DESC LIMIT
                    1)                                                                                    AS 'piston_b_px',
       GROUP_CONCAT(CASE WHEN k.name = 'piston_diff' THEN v.value END ORDER BY v.created_at DESC LIMIT
                    1)                                                                                    AS 'piston_diff'
FROM devices_health_status_keys k
       LEFT JOIN devices_health_status_values v on k.id = v.health_status_id
       LEFT JOIN devices d on v.device_id = d.id
WHERE d.type_id = 4
GROUP BY v.created_at, d.id
ORDER BY d.id;;


CREATE or replace VIEW player_data_table_step1 as
SELECT pp.id               as player_id,
       gpma.id             as application_id,
       case
         when timestampdiff(minute, gpma.starts_at, gpma.expires_at) != gpm.default_play_duration and
              gpm.default_play_duration > 0
           then concat(gpm.name, ' (',
                       case
                         when timestampdiff(minute, gpma.starts_at, gpma.expires_at) >
                              gpm.default_play_duration
                           then '+'
                         else
                           ''
                         end,
                       timestampdiff(minute, gpma.starts_at, gpma.expires_at) - gpm.default_play_duration,
                       'min)'
           )
         else gpm.name end as game_play_mode_name
FROM players pp
       inner JOIN game_play_mode_applications gpma on gpma.player_id = pp.id
       inner JOIN game_play_modes gpm
                  on gpma.game_play_mode_id = gpm.id and gpma.starts_at < CURRENT_TIMESTAMP < gpma.expires_at
WHERE current_timestamp BETWEEN gpma.starts_at and gpma.expires_at
GROUP BY pp.id, gpma.id;;


create or replace view player_data_table as
SELECT p.id                                             as player_id,
       u.id                                             as user_id,
       u.name                                           as user_name,
       u.username                                       as user_username,
       p.name                                           as player_name,
       r.value                                          as player_rfid,
       p.avatar_id                                      as avatar_id,
       a.img                                            as player_img,
       p.synchronized_at                                as player_synchronized_at,
       group_concat(game_play_mode_name separator ', ') as game_play_mode_name
FROM players p
       INNER JOIN users u ON u.id = p.user_id
       LEFT JOIN avatars a ON p.avatar_id = a.id
       LEFT JOIN rfids r ON p.rfid_id = r.id
       left join player_data_table_step1 s1 on p.id = s1.player_id
GROUP BY p.id;;


CREATE or replace VIEW game_log_data_table as
SELECT pp.id,
       a.img               as avatar,
       p.name                 player,
       pp.coefficient,
       pp.score,
       pp.time             as `time`,
       sg.is_time_excluded as timeExcluded,
       sb.name             as game,
       pp.created_at       as `date`
FROM plays AS pp
       LEFT JOIN players AS p ON p.id = pp.player_id
       INNER JOIN sub_games AS sb ON sb.id = pp.sub_game_id
       LEFT JOIN avatars AS a ON a.id = p.avatar_id
       left join sub_games sg on pp.sub_game_id = sg.id
WHERE pp.is_deleted = false
;;

SET SQL_MODE = @OLD_SQL_MODE;;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;;
SET GLOBAL log_bin_trust_function_creators = 0;